package org.mariuxdeangelo.masterthesis.database.modelsView;

public enum EndpointType {
    RETRIEVE_SBOM_DATA,
    RETRIEVE_SBOM_METADATA_BY_PROJECT,
    RETRIEVE_SBOM_METADATA_BY_FILE,
    RETRIEVE_DEPENDENCY_LIST_BY_NAME,
    RETRIEVE_DEPENDENCY_LIST_BY_NAME_VERSION,
    RETRIEVE_DEPENDENCY_LIST_BY_REF_LOC,
    RETRIEVE_DEPENDENCY_LIST_BY_REF_LOC_VERSION,
    RETRIEVE_CDX_DEPENDENCY_LIST_BY_NAME,
    RETRIEVE_CDX_DEPENDENCY_LIST_BY_NAME_VERSION,
    RETRIEVE_CDX_DEPENDENCY_LIST_BY_PURL,
    RETRIEVE_CDX_DEPENDENCY_LIST_BY_PURL_VERSION,
    RETRIEVE_SPDX_INSIGHTS_FOR_FILE,
    RETRIEVE_SPDX_INSIGHTS_FOR_PROJECT,
    RETRIEVE_LICENSE_LIST,
    DOWNLOAD_SBOM_FILE,
    DOWNLOAD_SHELL_LOG_FILE
}
