version: '3'
services:
  generator:
    image: "sbom-generators"
    privileged: true
    environment:
      - GENERATOR_BASEDIR=/app
      - THREADPOOL_SIZE=1
      - DEFAULT_TIMEOUT=300
      - DB_USER=
      - DB_PASSWORD=
      - DB_URL=
    volumes:
      - ~/Desktop/generators:/app